"""AWS databases

Revision ID: 11f2e3f0c0ae
Revises: 
Create Date: 2020-06-18 09:52:51.087970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f2e3f0c0ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('usertype', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_usertype'), 'users', ['usertype'], unique=False)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_usertype'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.Column('booktype', sa.String(length=20), nullable=False),
    sa.Column('genres', sa.String(length=256), nullable=False),
    sa.Column('synopsis', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_author'), 'products', ['author'], unique=False)
    op.create_index(op.f('ix_products_booktype'), 'products', ['booktype'], unique=False)
    op.create_index(op.f('ix_products_genres'), 'products', ['genres'], unique=False)
    op.create_index(op.f('ix_products_image'), 'products', ['image'], unique=True)
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    op.create_index(op.f('ix_products_title'), 'products', ['title'], unique=True)
    op.create_table('wishlists',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['customers.id'], )
    )
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlists')
    op.drop_index(op.f('ix_products_title'), table_name='products')
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.drop_index(op.f('ix_products_image'), table_name='products')
    op.drop_index(op.f('ix_products_genres'), table_name='products')
    op.drop_index(op.f('ix_products_booktype'), table_name='products')
    op.drop_index(op.f('ix_products_author'), table_name='products')
    op.drop_table('products')
    op.drop_table('customers')
    # ### end Alembic commands ###


def upgrade_libraries():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('booktype', sa.String(length=20), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_products_author'), 'library_products', ['author'], unique=False)
    op.create_index(op.f('ix_library_products_booktype'), 'library_products', ['booktype'], unique=False)
    op.create_index(op.f('ix_library_products_image'), 'library_products', ['image'], unique=True)
    op.create_index(op.f('ix_library_products_title'), 'library_products', ['title'], unique=True)
    op.create_table('comics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('page_num', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['library_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comics_filename'), 'comics', ['filename'], unique=False)
    op.create_table('libraries',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['library_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['library_customers.id'], )
    )
    # ### end Alembic commands ###


def downgrade_libraries():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libraries')
    op.drop_index(op.f('ix_comics_filename'), table_name='comics')
    op.drop_table('comics')
    op.drop_index(op.f('ix_library_products_title'), table_name='library_products')
    op.drop_index(op.f('ix_library_products_image'), table_name='library_products')
    op.drop_index(op.f('ix_library_products_booktype'), table_name='library_products')
    op.drop_index(op.f('ix_library_products_author'), table_name='library_products')
    op.drop_table('library_products')
    op.drop_table('library_customers')
    # ### end Alembic commands ###


def upgrade_transactions():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trans_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trans_products_image'), 'trans_products', ['image'], unique=True)
    op.create_index(op.f('ix_trans_products_title'), 'trans_products', ['title'], unique=True)
    op.create_table('trans_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trans_users_email'), 'trans_users', ['email'], unique=True)
    op.create_index(op.f('ix_trans_users_first_name'), 'trans_users', ['first_name'], unique=False)
    op.create_index(op.f('ix_trans_users_last_name'), 'trans_users', ['last_name'], unique=False)
    op.create_index(op.f('ix_trans_users_phone_number'), 'trans_users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_trans_users_username'), 'trans_users', ['username'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.Column('datestamp', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['trans_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('datestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['trans_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['trans_products.id'], )
    )
    op.create_table('payment_proof',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_name', sa.String(length=256), nullable=False),
    sa.Column('bank_name', sa.String(length=128), nullable=False),
    sa.Column('exact_money', sa.Integer(), nullable=False),
    sa.Column('transfer_datetime', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_proof_bank_account_name'), 'payment_proof', ['bank_account_name'], unique=False)
    op.create_index(op.f('ix_payment_proof_bank_name'), 'payment_proof', ['bank_name'], unique=False)
    op.create_table('trans_items',
    sa.Column('trans_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['trans_products.id'], ),
    sa.ForeignKeyConstraint(['trans_id'], ['transactions.id'], )
    )
    # ### end Alembic commands ###


def downgrade_transactions():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trans_items')
    op.drop_index(op.f('ix_payment_proof_bank_name'), table_name='payment_proof')
    op.drop_index(op.f('ix_payment_proof_bank_account_name'), table_name='payment_proof')
    op.drop_table('payment_proof')
    op.drop_table('order_items')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_trans_users_username'), table_name='trans_users')
    op.drop_index(op.f('ix_trans_users_phone_number'), table_name='trans_users')
    op.drop_index(op.f('ix_trans_users_last_name'), table_name='trans_users')
    op.drop_index(op.f('ix_trans_users_first_name'), table_name='trans_users')
    op.drop_index(op.f('ix_trans_users_email'), table_name='trans_users')
    op.drop_table('trans_users')
    op.drop_index(op.f('ix_trans_products_title'), table_name='trans_products')
    op.drop_index(op.f('ix_trans_products_image'), table_name='trans_products')
    op.drop_table('trans_products')
    # ### end Alembic commands ###


def upgrade_carts():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_products_image'), 'cart_products', ['image'], unique=True)
    op.create_index(op.f('ix_cart_products_title'), 'cart_products', ['title'], unique=True)
    op.create_table('carts',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['cart_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['cart_customers.id'], )
    )
    # ### end Alembic commands ###


def downgrade_carts():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carts')
    op.drop_index(op.f('ix_cart_products_title'), table_name='cart_products')
    op.drop_index(op.f('ix_cart_products_image'), table_name='cart_products')
    op.drop_table('cart_products')
    op.drop_table('cart_customers')
    # ### end Alembic commands ###

