"""Payment Proofs

Revision ID: 38642564f42b
Revises: 6fc7fa3b50e8
Create Date: 2020-06-22 00:22:38.433345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38642564f42b'
down_revision = '6fc7fa3b50e8'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_libraries():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_libraries():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_transactions():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_proofs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_name', sa.String(length=256), nullable=False),
    sa.Column('bank_name', sa.String(length=256), nullable=False),
    sa.Column('exact_money', sa.Integer(), nullable=False),
    sa.Column('transfer_date', sa.String(length=128), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_proofs_bank_account_name'), 'payment_proofs', ['bank_account_name'], unique=False)
    op.create_index(op.f('ix_payment_proofs_bank_name'), 'payment_proofs', ['bank_name'], unique=False)
    # ### end Alembic commands ###


def downgrade_transactions():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_proofs_bank_name'), table_name='payment_proofs')
    op.drop_index(op.f('ix_payment_proofs_bank_account_name'), table_name='payment_proofs')
    op.drop_table('payment_proofs')
    # ### end Alembic commands ###


def upgrade_carts():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_carts():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

